account/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('signup/', views.SignUpView.as_view(), name='signup'),
    path('delete_confirm', TemplateView.as_view(template_name='registration/delete_confirm.html'), name='delete-confirmation'),
    path('delete_complete', views.DeleteView.as_view(), name='delete-complete'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from account.views import Top
from .views import emailfunc

urlpatterns = [
    path('', Top.as_view(), name='top'),
    path('admin/', admin.site.urls),
    path('accounts/', include('account.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('sancom_free/', include('sancom_free.urls')),
    path('email/', emailfunc),
]

account/models.py
from django.contrib.auth.models import AbstractBaseUser, UserManager, PermissionsMixin
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone


#流用
class UserManager(UserManager):
    def _create_user(self, email, password, **extra_fields):
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)

#流用
class User(AbstractBaseUser, PermissionsMixin):

    email = models.EmailField(_('email address'), unique=True)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)


#自作
class File(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='login_user')
    filename1 = models.CharField(max_length=20)
    filename2 = models.CharField(max_length=20)
    filename3 = models.CharField(max_length=20)    

    def __str__(self):
        return '<' + self.filename1 + '(' + str(self.owner) + ')>'

account/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class UserCreateForm(UserCreationForm):

    class Meta:
        model = User
        if User.USERNAME_FIELD == 'email':
            fields = ('email',)
        else:
            fields = ('username', 'email')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

account/views.py
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import (
     get_user_model, logout as auth_logout,
)
from .forms import UserCreateForm
from .models import User, File
import openpyxl

User = get_user_model()


class Top(generic.TemplateView):
    params = {
        'visiter':''
    }

    def get(self, *args, **kwargs):
        if self.request.user.is_authenticated:
            id = str(self.request.user.id)
            user_name= self.request.user.get_username()
            if not File.objects.filter(owner=self.request.user).exists():
                file = File()
                file.owner = User.objects.filter(email=user_name).first()
                file.filename1 = 'SancomContents_' + id + '.xlsx'
                file.filename2 = 'voa_' + id + '.xlsx'
                file.filename3 = 'librivox_' + id + '.xlsx'

                wb=openpyxl.load_workbook("./static/SancomContents.xlsx")
                #wb=openpyxl.load_workbook("./static/voa.xlsx")
                #wb=openpyxl.load_workbook("./static/librivox.xlsx")
                wb.save("./static/" + file.filename1)
                #wb.save("./static/" + file.filename2)
                #wb.save("./static/" + file.filename3)
                file.save()
            self.params['visiter'] = user_name
        return render(self.request,'index.html', self.params) # top から index へ変更


#class Top(generic.TemplateView):
    #template_name = 'top.html'


class SignUpView(generic.CreateView):
    form_class = UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'


class ProfileView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        return render(self.request,'registration/profile.html')


class DeleteView(LoginRequiredMixin, generic.View):

    def get(self, *args, **kwargs):
        user = User.objects.get(email=self.request.user.email)
        user.is_active = False
        user.save()
        auth_logout(self.request)
        return render(self.request,'registration/delete_complete.html')

account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="{% static "css/custom.css" %}" rel="stylesheet" />
    <title>django-account</title>
</head>
<body>
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
    <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'top' %}">sancom</a></h5>

    <nav class="my-2 my-md-0 mr-md-3">
    {% if user.is_authenticated %}
        <a class="btn btn-outline-primary btn-sm mr-2" href="{% url 'accounts:profile' %}">マイページ</a>
    {% else %}
        <a class="btn btn-outline-primary btn-sm mr-2" href="{% url 'login' %}">ログイン</a>
        <a class="btn btn-outline-primary btn-sm" href="{% url 'accounts:signup' %}">入会</a>
    {% endif %}
    </nav>
</div>

<div class="container mt-3">
    {% block body %}{% endblock %}
</div>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js"
        integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
        integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
        crossorigin="anonymous"></script>
</body>
</html>

account/templates/base_centered.html
{% extends "base.html" %}

{% block body %}
    
    <div class="row text-center">
        <div class="col-sm-9 col-md-7 col-lg-5 mx-auto">
            <div class="card card-signin my-5">
                <div class="card-body">

                    {% block content %}{% endblock %}

                </div>
            </div>
        </div>
    </div>

{% endblock %}

account/templates/index.html
{% extends "base.html" %}

{% block body %}

    {% if user.is_authenticated %}
        <p>こんにちは　{{visiter}} さん</p>
        <br>
        <h4>フリーコンテンツ</h4>
        <ul>
            <li class="h5 mb-3"><a href="{% url 'sancomcontents' %}">日英中ビジネス文例(基本文例暗唱型)</a></li>
            <li class="h5 mb-3"><a href="{% url 'publiccontents' %}">一般公開コンテンツ(シャドーイング訓練型)</a></li>
        </ul>
        <h4>有料コンテンツ</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
        <h4>オンライン発音コーチング</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
        <h4>SANCOM専用SNS</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
    {% else %}
    <br>
    <h5 class="h6 mb-3" >ご会員様</h4>
    <ul>
        <li class="h6 mb-3">右上の「ログイン」よりお進みください。</li>
    </ul>
    <h5 class="h6 mb-3" >入会を希望される方</h4>
    <ul>
        <li class="h6 mb-3">右上の「入会」にてお手続きください。</li>
        <li class="h6 mb-3">費用は発生しません。</li>
        <li class="h6 mb-3">パスワード再発行時の認証のためEメールアドレスが必要になります。</li>
        <li class="h6 mb-3">入会後、フリーコンテンツをご利用いただけます。</li>
        <li class="h6 mb-3">SANCOMが提供する付加価値（一部）をお確かめください。</li>
    </ul>

    {% endif %}

{% endblock %}

account/templates/top.html
{% extends "base.html" %}

{% block body %}

    {% if user.is_authenticated %}
        <p>こんにちは　{{visiter}} さん</p>
        <br>
        <h4>フリーコンテンツ</h4>
        <ul>
            <li class="h5 mb-3"><a href="{% url 'index' %}">日英中ビジネス文例(基本文例暗唱型)</a></li>
            <li class="h5 mb-3"><a href="{% url 'publiccontents' %}">一般公開コンテンツ(シャドーイング訓練型)</a></li>
        </ul>
        <h4>有料コンテンツ</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
        <h4>オンライン発音コーチング</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
        <h4>SANCOM専用SNS</h4>
        <ul>
            <li class="h5 mb-3">準備中</li>
        </ul>
    {% else %}
    <h4>フリーコンテンツ</h4>
    <ul>
        <li class="h5 mb-3">日英中ビジネス文例(基本文例暗唱型)</li>
        <li class="h5 mb-3">一般公開コンテンツ(シャドーイング訓練型)</li>
    </ul>
    <h4>有料コンテンツ</h4>
    <ul>
        <li class="h5 mb-3">準備中</li>
    </ul>
    <h4>オンライン発音コーチング</h4>
    <ul>
        <li class="h5 mb-3">準備中</li>
    </ul>
    <h4>SANCOM専用SNS</h4>
    <ul>
        <li class="h5 mb-3">準備中</li>
    </ul>
    <h4>※ご入会(無料)によりフリーコンテンツをご利用いただけます。パスワード再発行時の認証のためIDとしてEメールアドレスが必要になります。</h4>
    {% endif %}

{% endblock %}